"""v6.41.0 新增 Europe PMC 引擎：解析必须照真接口返回的形状来。

夹具来源（取证时间与方式）：2026-09-29 用宿主 WebFetch 打
`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=...&format=json&resultType=core`
取回的两条**逐字**记录（API version 6.9）——
  · `_ITEM_MED_ONLY`：`isOpenAccess=N`、只有 DOI 全文链接（PMID 42748453）
  · `_ITEM_OA`：`isOpenAccess=Y`、带 `pmcid` 与 Europe_PMC 的 html/pdf 两条 OA 链接（PMID 42640622）
本机 curl 当时对整条 `/rest/*` 前缀恒回 HTTP 503（换网络出口才取到），所以「通道挂了要回 None」
这一条也有真件依据，不是设想。

为什么两条都要留：全文链接的优先级（OA 的 europepmc 页 vs 订阅论文的 doi 页）只有对着
真 returned `fullTextUrlList` 才判得出来——只测其中一条，另一条的分支等于没测。
"""

import json
import urllib.parse

import pytest

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import engines.academic_engines as ae  # noqa: E402


_ITEM_MED_ONLY = {
    "id": "42748453", "source": "MED", "pmid": "42748453",
    "doi": "10.2196/93761",
    "title": "Retrieve-Then-Verify for Evaluating Evidence Support and Hallucination in "
             "Large Language Model-Generated Medical Information: Empirical Study.",
    "authorString": "Liang Z, Sheffield C, Butera G, Antani S.",
    "authorList": {"author": [
        {"fullName": "Liang Z", "lastName": "Liang", "firstName": "Zhaohui",
         "authorId": {"type": "ORCID", "value": "0000-0002-9361-5535"}},
        {"fullName": "Sheffield C", "lastName": "Sheffield", "firstName": "Cynthia"},
        {"fullName": "Butera G", "lastName": "Butera", "firstName": "Gisela"},
        {"fullName": "Antani S", "lastName": "Antani", "firstName": "Sameer"}]},
    "journalInfo": {
        "volume": "5", "journalIssueId": 4253449, "dateOfPublication": "2026 Sep",
        "yearOfPublication": 2026,
        "journal": {"medlineAbbreviation": "JMIR AI", "title": "JMIR AI",
                    "essn": "2817-1705", "issn": "2817-1705", "nlmid": "9918645789006676",
                    "isoabbreviation": "JMIR AI"},
        "printPublicationDate": "2026-09-01"},
    "pubYear": "2026", "pageInfo": "e93761",
    "abstractText": "<h4>Background</h4>Despite high reported accuracy on clinical and "
                    "evidence appraisal tasks, AI-generated medical information may lack "
                    "explicit support from sources.",
    "publicationStatus": "epublish", "language": "eng", "pubModel": "Electronic",
    "pubTypeList": {"pubType": ["Journal Article"]},
    "keywordList": {"keyword": ["Hallucinations", "Large Language Models", "evidence-based medicine"]},
    "fullTextUrlList": {"fullTextUrl": [
        {"availability": "Subscription required", "availabilityCode": "S",
         "documentStyle": "doi", "site": "DOI", "url": "https://doi.org/10.2196/93761"}]},
    "isOpenAccess": "N", "inEPMC": "N", "inPMC": "N", "citedByCount": 0,
    "hasReferences": "N", "hasPDF": "N",
    "electronicPublicationDate": "2026-09-16", "firstPublicationDate": "2026-09-16",
}

_ITEM_OA = {
    "id": "42640622", "source": "MED", "pmid": "42640622", "pmcid": "PMC13506236",
    "fullTextIdList": {"fullTextId": ["PMC13506236"]},
    "doi": "10.1097/cce.0000000000001474",
    "title": "Hallucination Rate of Peer-Reviewed Citations Generated by Large Language "
             "Models in Neurocritical Care.",
    "authorString": "Seifi A, Seyfi A.",
    "authorList": {"author": [
        {"fullName": "Seifi A", "lastName": "Seifi", "firstName": "Ali"},
        {"fullName": "Seyfi A", "lastName": "Seyfi", "firstName": "Ali"}]},
    "journalInfo": {"issue": "9", "volume": "8", "yearOfPublication": 2026,
                    "journal": {"medlineAbbreviation": "Crit Care Explor",
                                "title": "Critical care explorations", "essn": "2639-8028",
                                "issn": "2639-8028", "isoabbreviation": "Crit Care Explor",
                                "nlmid": "101746347"},
                    "printPublicationDate": "2026-09-01"},
    "pubYear": "2026", "pageInfo": "e1474",
    "abstractText": "<h4>Importance</h4>Large language models (LLMs) are increasingly used "
                    "for scientific literature retrieval, yet their citation accuracy remains "
                    "unverified.",
    "pubTypeList": {"pubType": ["research-article", "Journal Article"]},
    "meshHeadingList": {"meshHeading": [
        {"majorTopic_YN": "N", "descriptorName": "Humans"},
        {"majorTopic_YN": "Y", "descriptorName": "Large Language Models"}]},
    "keywordList": {"keyword": ["Citation Hallucination", "Fabricated References"]},
    "fullTextUrlList": {"fullTextUrl": [
        {"availability": "Subscription required", "availabilityCode": "S",
         "documentStyle": "doi", "site": "DOI", "url": "https://doi.org/10.1097/CCE.0000000000001474"},
        {"availability": "Open access", "availabilityCode": "OA", "documentStyle": "html",
         "site": "Europe_PMC", "url": "https://europepmc.org/articles/PMC13506236"},
        {"availability": "Open access", "availabilityCode": "OA", "documentStyle": "pdf",
         "site": "Europe_PMC", "url": "https://europepmc.org/articles/PMC13506236?pdf=render"}]},
    "isOpenAccess": "Y", "inEPMC": "Y", "inPMC": "Y", "citedByCount": 0,
    "hasReferences": "Y", "hasPDF": "Y", "license": "cc by",
    "electronicPublicationDate": "2026-08-25", "firstPublicationDate": "2026-08-25",
}


def _payload(*items):
    return json.dumps({
        "version": "6.9", "hitCount": len(items),
        "nextCursorMark": "AoIIQL9jUig1NjMwOTE2MA==",
        "request": {"query": "test", "pageSize": "2",
                    "resultType": "core", "accept": "application/json"},
        "resultList": {"result": list(items)},
    }).encode("utf-8")


@pytest.fixture
def fake_get(monkeypatch):
    """把 _http_get 换成假件，记下发出去的 URL；返回什么由用例决定。"""
    calls = []

    def _install(body):
        def fake(url, **kwargs):
            calls.append(url)
            return body
        monkeypatch.setattr(ae, '_http_get', fake)
        return calls
    return _install


def _engine():
    return ae.EuropePmcEngine()


# ------------------------------------------------------------------ 元数据与接线

def test_metadata_says_no_config_is_required():
    """无 key 的源不能把 config_keys 写成阻塞项——实测会把用户支去申请一个用不上的 key。"""
    meta = _engine().metadata
    assert meta.name == 'europepmc'
    assert meta.layer == 1
    assert meta.requires_config is False
    assert 'search' in meta.capabilities and 'academic' in meta.capabilities


def test_engine_is_registered_and_probeable():
    """注册表与探针表都要有它，否则它只是一段永远不会被调用的死代码。"""
    from research import build_registry
    from probe import PROBE_QUERIES
    registry = build_registry()
    assert registry.get('europepmc') is not None
    assert 'europepmc' in PROBE_QUERIES, '未登记探针＝闸门看不见这个源今天出不导出数据'


def test_full_text_domain_is_tier_1():
    """europepmc.org 是同行评审全文的正式存档站，与 pubmed 同级；漏登记会被降到 Tier 3。"""
    from tier import domain_tier
    assert domain_tier('https://europepmc.org/articles/PMC13506236') == 1


# ------------------------------------------------------------------ 解析真件

def test_open_access_item_prefers_europe_pmc_full_text_url(fake_get):
    calls = fake_get(_payload(_ITEM_OA))
    res = _engine().search("hallucination", max_results=2)
    assert len(res) == 1
    r = res[0]
    assert r.url == "https://europepmc.org/articles/PMC13506236"
    assert r.title.startswith("Hallucination Rate of Peer-Reviewed Citations")
    assert r.source == 'europepmc' and r.engine == 'europepmc'
    assert r.author == "Seifi A; Seyfi A"
    assert r.published_date == "2026-08-25"
    assert len(calls) == 1


def test_subscription_only_item_falls_back_to_doi_url(fake_get):
    """没有 OA 链接时退回 doi——退回订阅墙前的 landing 页会让反查读不到正文。"""
    fake_get(_payload(_ITEM_MED_ONLY))
    r = _engine().search("hallucination")[0]
    assert r.url == "https://doi.org/10.2196/93761"
    assert r.raw['doi'] == "10.2196/93761"          # 裸 DOI，档 B 跨标识符判等靠它
    assert r.raw['pmid'] == "42748453"
    assert 'pmcid' not in r.raw or not r.raw.get('pmcid')


def test_journal_and_citation_count_land_in_normalized_raw_keys(fake_get):
    """评分器读 venue/citation_count/published_date，原生键名不一样就必须归一（实测踩过）。"""
    fake_get(_payload(_ITEM_MED_ONLY))
    raw = _engine().search("hallucination")[0].raw
    assert raw['venue'] == "JMIR AI"
    assert raw['citation_count'] == 0               # 真件就是这个值，缺项才不许印 0
    assert raw['published_date'] == "2026-09-16"
    assert raw['issn'] == "2817-1705"


def test_abstract_html_is_stripped_but_keywords_kept(fake_get):
    fake_get(_payload(_ITEM_MED_ONLY))
    content = _engine().search("hallucination")[0].content
    assert '<h4>' not in content and '</h4>' not in content
    assert 'Despite high reported accuracy' in content
    assert 'Large Language Models' in content        # keywordList 要能进片段


def test_mesh_headings_appear_when_present(fake_get):
    """MeSH 词只有 MED 条目才有（真件里非 OA 那条就没有）；两条都要能过。"""
    fake_get(_payload(_ITEM_OA))
    content = _engine().search("hallucination")[0].content
    assert 'Large Language Models' in content
    fake_get(_payload(_ITEM_MED_ONLY))
    assert '[MeSH]' not in _engine().search("hallucination")[0].content


def test_result_records_the_query_actually_sent(fake_get):
    """命中必须能解释：SearchResult.query 记的是真发出去的那句（旧版断链踩过）。"""
    fake_get(_payload(_ITEM_MED_ONLY))
    r = _engine().search("citation hallucination", max_results=2)[0]
    assert r.query == "citation hallucination"


# ------------------------------------------------------------------ 请求构造

def test_request_url_carries_format_resulttype_pagesize_and_query(fake_get):
    calls = fake_get(_payload())
    _engine().search("hallucination rate of citations", max_results=7)
    parsed = urllib.parse.urlparse(calls[0])
    q = urllib.parse.parse_qs(parsed.query)
    assert parsed.scheme == 'https' and parsed.netloc == 'www.ebi.ac.uk'
    assert q['format'] == ['json'] and q['resultType'] == ['core']
    assert q['pageSize'] == ['7']
    assert q['query'] == ['hallucination rate of citations']


def test_pagesize_is_capped_at_the_api_limit(fake_get):
    """接口 pageSize 上限 1000，超了直接 400——不能把调用方给的数原样塞进去。"""
    calls = fake_get(_payload())
    _engine().search("test", max_results=5000)
    q = urllib.parse.parse_qs(urllib.parse.urlparse(calls[0]).query)
    assert int(q['pageSize'][0]) <= 1000


# ------------------------------------------------------------------ 失败与空结果分开

def test_http_failure_returns_none_not_empty_list(fake_get):
    """通道挂了必须回 None（断路器据此记失败）；实测本机对整条 rest/ 前缀 503。"""
    fake_get(None)
    assert _engine().search("hallucination") is None


def test_empty_result_list_returns_empty_list(fake_get):
    """hitCount=0 是「调通了但没命中」，不是故障——回 None 会把 0 命中报成引擎坏了。"""
    fake_get(_payload())
    assert _engine().search("一个不存在的词组") == []


def test_non_json_body_returns_none(fake_get):
    """网关页（503 的 HTML）不是 JSON：不能当成 0 命中静默放过。"""
    fake_get(b"<html><head><title>503 Service Temporarily Unavailable</title></head></html>")
    assert _engine().search("hallucination") is None
